### ISSUE TITLE
App crashes when using Tablet (Simulator - Nexus 10)

### ISSUE THREAD

**Issue by tomglanville** [jiscdev/study-goal#122]
See log below:

`E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.studygoal.jisc, PID: 4954
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.studygoal.jisc/com.studygoal.jisc.LoginActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                      at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4519)
                      at android.app.ActivityThread.-wrap19(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
                      at com.studygoal.jisc.LoginActivity.onCreate(LoginActivity.java:452)
                      at android.app.Activity.performCreate(Activity.java:6679)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                      at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4519) 
                      at android.app.ActivityThread.-wrap19(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6119) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
I/art: Do partial code cache collection, code=248KB, data=190KB
I/art: After code cache collection, code=248KB, data=190KB
I/art: Increasing code cache capacity to 1024KB
Disconnected from the target VM, address: 'localhost:8618', transport: 'socket'
`

**Comment by mparker-tbox** [comment]
Happening because tablet view is missing from changed login screen. Fixed on develop, need to update login_v2.

**Comment by tomglanville** [comment]
Will keep this issue open until login_v2 is fixed.

**Comment by tomglanville** [comment]
Appears to be fixed in **login_v2** branch.
