### ISSUE TITLE
Samsumg Galaxy S6 crashes when photo taken for profile picture

### ISSUE THREAD

**Issue by tomglanville** [jiscdev/study-goal#139]
Other devices I've tested on appear OK.

The Samsung Galaxy S6 crashes with the error below:

`06-21 08:08:11.939 14502-14502/com.studygoal.jisc E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.studygoal.jisc, PID: 14502
                                                                    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=100, result=-1, data=null} to activity {com.studygoal.jisc/com.studygoal.jisc.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Bundle android.content.Intent.getExtras()' on a null object reference
                                                                        at android.app.ActivityThread.deliverResults(ActivityThread.java:4472)
                                                                        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4515)
                                                                        at android.app.ActivityThread.-wrap22(ActivityThread.java)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1687)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
                                                                     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Bundle android.content.Intent.getExtras()' on a null object reference
                                                                        at com.studygoal.jisc.MainActivity.onActivityResult(MainActivity.java:711)
                                                                        at android.app.Activity.dispatchActivityResult(Activity.java:7256)
                                                                        at android.app.ActivityThread.deliverResults(ActivityThread.java:4468)
                                                                        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4515) 
                                                                        at android.app.ActivityThread.-wrap22(ActivityThread.java) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1687) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:154) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6682) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) `

**Comment by tomglanville** [comment]
I'll test this on S6

**Comment by tomglanville** [comment]
Crash fixed but have noted a few improvements to photos here: https://github.com/jiscdev/study-goal/issues/147
